name: 'GitHub Actions DZqiandao Bot'
# UTC16:01(北京UTC+8 00:01点)触发任务
on:
  push:
  schedule:
    - cron: '1 16 * * *'

jobs:
  curl-discuz:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
          USER_AGENT: ${{ secrets.USER_AGENT }}
          COOKIE: ${{ secrets.COOKIE }}
          #DZ论坛的防攻击机制验证码
          FORMHASH: ${{ secrets.FORMHASH }}
         # 向站点发送 GET 请求
         run:                                 
          curl -A "$USER_AGENT" -b "$COOKIE" "https://bbs.binmt.cc/k_misign-sign.html?operation=qiandao&format=button&formhash=$FORMHASH&inajax=1&ajaxtarget=midaben_sign"
